require('jquery') ;
require('leaflet') ;

require('./purpleAirMarkerLayer.js') ;
require('./purpleLayer.js') ;
require('./fractracker.js') ;
require('./skyTruthLayer.js') ;
require('./odorReportLayer.js') ;
require('./mapKnitterLayer.js') ;
require('./toxicReleaseLayer.js') ;
require('leaflet-providers') ;
require('./openWeatherMapLayer.js') ;
require('./aqicnLayer.js');
require('./openaqLayer.js');
require('./osmLandfillMineQuarryLayer.js');
require('./wisconsinLayer.js');
require('./fracTrackerMobileLayer.js');
require('./pfasLayer.js');
require('./luftdatenLayer.js');
require('./openSenseLayer.js');
require('./indigenousLayers.js');
